<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QAQC</name>
   <tag></tag>
   <elementGuidId>d1ad6568-a243-4db8-8318-77d0291527cd</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>A5b657a77443a4f8fa316895424c54ee6117</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QAQC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P289d15460c3c4d26bb4da380ee8b4344_1_oReportCell&quot;)/table[1]/tbody[1]/tr[2]/td[@class=&quot;A5b657a77443a4f8fa316895424c54ee6188xBc&quot;]/table[@class=&quot;A5b657a77443a4f8fa316895424c54ee6188xB&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;P289d15460c3c4d26bb4da380ee8b4344_1_r10&quot;]/tbody[1]/tr[4]/td[3]/table[@class=&quot;A5b657a77443a4f8fa316895424c54ee6186&quot;]/tbody[1]/tr[28]/td[@class=&quot;A5b657a77443a4f8fa316895424c54ee6117c P289d15460c3c4d26bb4da380ee8b4344_1_r8&quot;]/div[@class=&quot;A5b657a77443a4f8fa316895424c54ee6117&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Reports/iframe</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//td[@id='P289d15460c3c4d26bb4da380ee8b4344_1_oReportCell']/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[4]/td[3]/table/tbody/tr[28]/td[5]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AV Ship Building Corporation and Heavy Industries India &amp; Singapore'])[3]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Devi 53'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QC'])[2]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Z11'])[3]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//tr[28]/td[5]/div</value>
   </webElementXpaths>
</WebElementEntity>
